##### Beginning of file

addons:
    apt:
        packages:
        # - pdf2svg
        - pgf
        - poppler-utils
        - texlive-binaries
        - texlive-latex-base
        # - texlive-latex-extra
        # - texlive-pictures

branches:
    except:
        - gh-pages

env:
    global:
        - DOCUMENTER_DEBUG="true"
    matrix:
        - GROUP="appveyor-1"

git:
    depth: 99999999

julia:
    - 0.6
    - 0.7
    - 1.0
    - nightly

language: julia

matrix:
    allow_failures:
        - julia: 0.7
        - julia: 1.0
        - julia: nightly
    fast_finish: true

notifications:
    email:
        on_success: always # default: change
        on_failure: always # default: always

os:
    - linux
    - osx

############################################################################

before_install: ./ci/travis/before_install.sh

script: ./ci/travis/script.sh

##### End of file
