## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## Allow failures on nightly julia:
matrix:
  allow_failures:
  - julia: nightly

env:
  global:
  - PYTHON=conda

addons:
  apt:
    packages:
    - hdf5-tools

#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

before_script:
  - julia -e 'Pkg.clone("https://github.com/bcbi/ClassImbalance.jl")'

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("AluthgeSinhaBase"); Pkg.test("AluthgeSinhaBase"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("AluthgeSinhaBase")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AluthgeSinhaBase")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
