## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## Allow failures on nightly julia:
matrix:
  allow_failures:
  - julia: nightly

env:
  global:
  - PYTHON=conda

addons:
  apt:
    packages:
    - hdf5-tools

before_script:
  - julia -e 'Pkg.clone("https://github.com/bcbi/ClassImbalance.jl")'
  - julia -e 'Pkg.clone("https://github.com/bcbi/AUC.jl")'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("AluthgeSinhaBase")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AluthgeSinhaBase")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
