##### Beginning of file

codecov:
    branch: develop

comment: true

ignore:
    # ignore PredictMD.Clean
    - "src/submodules/Clean"
    - "src/submodules/Clean/**/*"
    # ignore PredictMD.GPU
    - "src/submodules/GPU"
    - "src/submodules/GPU/**/*"

##### End of file
