codecov:
    branch: develop

comment: true

ignore:
    - "src/submodules/clean/hcup/hcup.jl"
    - "src/submodules/gpu/clang/clang.jl"
    - "src/submodules/gpu/clarrays/clarrays.jl"
    - "src/submodules/gpu/cuarrays/cuarrays.jl"
    - "src/submodules/gpu/cxx/cxx.jl"
    - "src/submodules/gpu/llvm/llvm.jl"
